version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Africa/Lagos
    open-pull-requests-limit: 5
    labels: ["type: dependencies", "area: go"]
    commit-message:
      prefix: "build(deps)"
    groups:
      go-minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Africa/Lagos
    open-pull-requests-limit: 5
    labels: ["type: dependencies", "area: ci"]
    commit-message:
      prefix: "ci(deps)"
    groups:
      actions-minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

